### ISSUE TITLE
verify that web page is ok

### ISSUE THREAD

**Issue by laszewsk** [mlcommons/science#43]
- [x] https://mlcommons.org/en/groups/research-science/
- [x] I think there was an elaboration on the mission statement. I think we integrated
- [x] To modify next version we we use this Web page https://github.com/laszewsk/mlcommons/blob/main/webpage/frontpage-v4.md
- [x] Gregor will upload as this is done on non public git repo by mlcommons

**Comment by juripapay** [comment]
Approved

**Comment by juripapay** [comment]
ok

**Comment by juripapay** [comment]
All tasks have been checked.

**Comment by juripapay** [comment]
issue closed, all tasks completed
